### ISSUE TITLE
AbstractMethodError 

### ISSUE THREAD

**Issue by ritesh-bsb** [fernandospr/java-wns#10]
I am getting abstract method error on sending push notification  : 

[java] java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
     [java] 	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
     [java] 	at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:71)
     [java] 	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:185)
     [java] 	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:70)
     [java] 	at ar.com.fernandospr.wns.client.WnsClient.push(WnsClient.java:128)
     [java] 	at ar.com.fernandospr.wns.WnsService.pushToast(WnsService.java:131)
     [java] 	at ar.com.fernandospr.wns.WnsService.pushToast(WnsService.java:119)
     [java] 	at com.bsb.portal.notification.WNSSender.pushNotification(WNSSender.java:36)
     [java]

**Comment by fernandospr** [comment]
@ritesh-bsb 
Please, provide more information.
What is the URL?
Which version of java-wns are you testing? Have you tested it with a previous version?
