### ISSUE TITLE
MalFormed Toast Templates

### ISSUE THREAD

**Issue by zmouhoubi** [fernandospr/java-wns#12]
Hi Fernando,
First i apologize for my average english.

Thank you for the java-wns api, it's a great job and help me to send notifications.

I would like submit a bug about the received notification, it's dosn't display the icon app and the text was always "New notification".  
when a use java-wns, the used Toast template 01 is like this : (`<toast><type>wns/toast</type><visual><binding template="ToastText01"><text><text id="1">Sample Text</text></text></binding></visual><audio/></toast>`) but in the toast template catalog [](https://msdn.microsoft.com/en-us/library/windows/apps/hh761494.aspx) the good one is (`<toast><visual><binding template="ToastText01"><text id="1">Sample Text</text></binding></visual></toast>`) (whith only one <text> tags not 2 like in the first one).
When i test the java-wns toast template text 01 on the Web App []((http://pushtestserver.azurewebsites.net/wns/)) i understand that the problem comes from the <text> tags,(the one just before <text id="1"...).

Do you know how can i remove the <text> tags that ares in plus ?

Thank you in advance  for your help.
Zahir.

**Comment by fernandospr** [comment]
Thanks @zmouhoubi, I will check this over the weekend.

**Comment by zmouhoubi** [comment]
Hi Fernando, have you takes few time to see if there à solution?

Thank you,

Zahir.

**Comment by fernandospr** [comment]
@zmouhoubi Please can you check if you have the problem with the 1.3 version?

**Comment by fernandospr** [comment]
@zmouhoubi I have seen the problem but could not fix it yet. Can you try the previous version of the library?

**Comment by zmouhoubi** [comment]
Hi Fernando,
Thank you for your response. 
I try the version 1.3 and it works so good, thank you very much. 

Have a nice day,
Zahir.

**Comment by fernandospr** [comment]
So it seems, 1.3.1 is not serializing the lists of elements correctly.

With 1.3.1: <text><text id="1">Hello world</text></text>
With older versions: <text id="1">Hello world</text>

So for now, you should use older version until I find the way to fix it.

**Comment by damiantone** [comment]
Hi all,

for remove the tag type you can add an annotation in class WnsToast in getType(). For example:

@Override
	@XmlTransient
	public String getType() {
		return WnsNotificationType.TOAST;
	}

Regards,

damiantone

**Comment by Sergio-Mira** [comment]
@fernandospr thanks for this lib! I've fixed the serialization here https://github.com/fernandospr/java-wns/pull/14

**Comment by fernandospr** [comment]
@Sergio-Mira Thanks!

**Comment by fernandospr** [comment]
1.3.2 will have this fix.

**Comment by twiedow** [comment]
@fernandospr Do you know when v1.3.2 will be released?

**Comment by fernandospr** [comment]
1.4.0 is being released right now to Maven Central! Just wait for a few hours.

**Comment by fernandospr** [comment]
Released.

**Comment by twiedow** [comment]
Thanks a lot!
