### ISSUE TITLE
Request access token returning HTTP error 500

### ISSUE THREAD

**Issue by Simimmo** [fernandospr/java-wns#13]
Hi Fernando,

The following request to get access token in WnsClient.refreshAccessToken is returning HTTP error 500

        ClientConfig clientConfig = new ClientConfig(JacksonJaxbXMLProvider.class, JacksonJsonProvider.class).connectorProvider(new ApacheConnectorProvider());
        clientConfig.property(ClientProperties.PROXY_URI, "http" + "://" + "proxy.host" + ":" + "8080");
        Client client = ClientBuilder.newClient(clientConfig);

        WebTarget target = client.target("https://login.live.com/accesstoken.srf");

        MultivaluedStringMap formData = new MultivaluedStringMap();
        formData.add("grant_type", "client_credentials");
        formData.add("client_id", "ms-app://client_id");
        formData.add("client_secret", "client_secret");
        formData.add("scope", "notify.windows.com");
        Response response = target.request(MediaType.APPLICATION_FORM_URLENCODED_TYPE).accept(MediaType.APPLICATION_JSON_TYPE).post(Entity.form(formData));

If I perform the request using the following code instead, it's returning 200 OK providing the token

        HttpPost post = new HttpPost("https://login.live.com/accesstoken.srf");
        List<NameValuePair> nvps = new ArrayList<NameValuePair>();

        nvps.add(new BasicNameValuePair("client_id", "ms-app://client_id"));
        nvps.add(new BasicNameValuePair("client_secret", "client_secret"));
        nvps.add(new BasicNameValuePair("scope", "notify.windows.com"));
        nvps.add(new BasicNameValuePair("grant_type", "client_credentials"));

        post.setEntity(new UrlEncodedFormEntity(nvps, Consts.UTF_8));

        post.addHeader("Content-Type", "application/x-www-form-urlencoded");
        post.addHeader("Accept", "application/json");

        CloseableHttpClient httpClient = HttpClients.createDefault();

        HttpHost proxy = new HttpHost("proxy.host", 8080, "http");
        RequestConfig rc = RequestConfig.custom().setSocketTimeout(1000).setConnectTimeout(1000).setProxy(proxy).build();
        post.setConfig(rc);

        CloseableHttpResponse response = httpClient.execute(post);

I'm using version java-wns 1.3.1 downloaded from Ivy. Could there be something wrong with the version of JAX-RS I'm using?

Thank you for your help.

**Comment by fernandospr** [comment]
Please, check with an older version. 1.3.1 has a few bugs that should be fixed in the following version.
