### ISSUE TITLE
[question] Is WnsService thread-safe ?

### ISSUE THREAD

**Issue by phil-mars** [fernandospr/java-wns#15]
Hello and thanks for this library !

I'm wondering whether WnsService is thread-safe. I looked at the code and saw javax.ws.rs package is used. I did not find a clear answer on the thread-safety of this package :
http://stackoverflow.com/questions/24700798/is-jax-rs-client-thread-safe
http://stackoverflow.com/questions/25401210/webtarget-and-thread-safety
http://stackoverflow.com/questions/18078666/is-java-jersey-2-1-client-thread-safe

What would you say ? :)
Thanks !

**Comment by fernandospr** [comment]
Because it is not clear enough, I would suggest to avoid multiple threads sharing the same WnsService.
