### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by chrisdoc** [fernandospr/java-wns#9]
Would it be possible to get the newest snapshot released to maven central.
Thank you

**Comment by yaniv-cb4** [comment]
Same request, can you publish 1.3.1-SNAPSHOT to maven repo?

**Comment by shawnfeldman** [comment]
same request here, we are using in apache usergrid but need your fasterxml dependencies

**Comment by charpin** [comment]
Same request too. The version 1.3 is too old. 

This version use an old libray *org.codehaus.jackson.jackson-jaxrs* that was moved to new group (*com.fasterxml.jackson.jaxrs*) and new artifact (*jackson-jaxrs-json-provider*).

This version can cause conflicts between the new artifact and the old artifact. Many Java librairies use now the new artifact. 

So, fernando, can you please to get the newest snapshot (or upgrade version to 1.4) released to maven central ?

Thanks in advance.

**Comment by fernandospr** [comment]
Hi all, ok I will release next weekend.

Thanks.

**Comment by fernandospr** [comment]
@charpin @shawnfeldman @yaniv-cb4 @chrisdoc I have uploaded a new version. In a few hours it will be available through Maven Central.
